### ISSUE TITLE
Urgent: API keys committed

### ISSUE THREAD

**Issue by rastapasta** [mkamdar/trade-bittrex#1]
Hey @mkamdar,

just to inform you: your API keys can easily be found with GitHub's search engine.

I would really love to urge you to disable your existing key to avoid any loss, as any black hat person might have already found it the same way I just did.

Save your BTC, NEO and PAY tokens ;)

Bests,
- Michael

**Comment by mkamdar** [comment]
Hi Micheal,

Thanks for your suggestion. Indeed it was a mistake I should have not done.
I have disabled it now. I came to know soon after i committed the code to
github, but it would still appear in history.

Thanks once again for bringing to my notice.

I have deleted the keys...:)

Regards,
Mufaddal

**Comment by mkamdar** [comment]
Hi Micheal,

Thanks for your suggestion. Indeed it was a mistake I should have not done.
I have disabled it now. I came to know soon after i committed the code to
github, but it would still appear in history.

Thanks once again for bringing to my notice.

I have deleted the keys...:)

Regards,
Mufaddal

**Comment by rastapasta** [comment]
Great and no worries, happens to the best :-)

Wishing luck for happy & successful trades,
Michael
